import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        height: '100%',
        display: 'flex',
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#C1AB73',
    },
    logo: {
        width: 180,
        height: 180,
        resizeMode: "contain",
        marginBottom: 80,
    },
    logov2: {
        height: 100,
        resizeMode: "contain",
        marginBottom: 50,
    },
    logoSingUp: {
        width: 180,
        height: 180,
        resizeMode: "contain",
        marginBottom: 50,
    },
    main: {
        flex: 1,
        backgroundColor: '#C1AB73',
        height: '100%',
    },
    loginButton: {
        backgroundColor:'#ffffff', 
        borderRadius:15, 
        width: '55%',
        padding: 12,
        marginTop: 25,
        alignItems:'center',
        justifyContent: 'center',
    },
    buttonText: {
        fontFamily: 'Inter-Black',
    },
    registerButton: {
        backgroundColor:'#C1AB73', 
        borderRadius:15, 
        borderColor: '#000000',
        borderWidth: 4,
        width: '55%',
        padding: 12,
        marginTop: 25,
        alignItems:'center',
        justifyContent: 'center',
    },
    signIn: {
        backgroundColor:'#C1AB73',
    },
    form: {
        backgroundColor: '#ffffff',
        borderRadius: 15,
        justifyContent: 'center',
        width: '70%',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        alignContent: 'center',
        marginTop: 15,
        marginBottom: 8,
    },
    formDescription: {
        width: '70%',
        height: '15%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        borderRadius: 15,
        marginTop: 10,
        marginBottom: 10,
    },
    customtextInput: {
        fontFamily: 'Inter-Black',
        color: '#C1AB73',
        width: '80%',
        fontSize: 12,
        padding: 9,
    },
    signInAuth: {
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        backgroundColor: '#000000',
        color:'#C1AB73',
        textAlign: 'center',
        padding: 10,
        fontFamily: 'Inter-Black',
        fontSize: 13,
        borderRadius: 15,
    },
    signUpAuth: {
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        backgroundColor: '#C1AB73',
        color:'#000000',
        textAlign: 'center',
        padding: 10,
        fontFamily: 'Inter-Black',
        fontSize: 13,
        borderRadius: 15,
        borderColor: '#000000',
        borderWidth: 4,
    },
    signInAuthContainer: {
        width: '50%',
        height: '5%',
        display: 'flex',
        alignItems: 'center',
        marginTop: 50,
    },
    inputDescription: {
        width: '100%',
        height: '100%',
        marginTop: 7,
        backgroundColor: '#ffffff',
        borderRadius: 10,
        padding: 13,
    },
    changeAuthMethod: {
        justifyContent: 'center',
        width: '70%',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        alignContent: 'center',
        marginTop: 15,
        marginBottom: 8,
    },
    scrollViewContent: {
        flexGrow: 1,
    }
});

export default styles;